apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: multi-steps

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
      
      
jobs:
  my-job-1:
    steps:
      - name: step 0
        uses: docker://alpine:3.18
        id: step0
        run: |
           echo "=== string before masking ==="
           echo "hello world"
           echo -n "hello" | cloudbees mask
           echo "=== string after masking ==="
           echo "hello world"
           
      - name: step1 - secrets masked from step 0 are also masked in this step 
        uses: docker://alpine:3.18
        id: step1
        run: |
           echo "=== string before masking ==="
           echo "hello world"
           echo -n "world" | cloudbees mask
           echo "=== string after masking ==="
           echo "hello world"

